ALTER TABLE PROPERTIES MODIFY PROPERTY_ID DEFAULT PROPERTIES_SEQ.NEXTVAL;
ALTER TABLE RENTAL_AGREEMENTS MODIFY RENTAL_ID DEFAULT RENTAL_AGREEMENTS_SEQ.NEXTVAL;
ALTER TABLE MAINTENANCE_REQUESTS MODIFY REQUEST_ID DEFAULT MAINTENANCE_REQUESTS_SEQ.NEXTVAL;
ALTER TABLE PROPERTY_LISTINGS MODIFY LISTING_ID DEFAULT PROPERTY_LISTINGS_SEQ.NEXTVAL;
ALTER TABLE PROPERTY_OWNERS MODIFY OWNER_ID DEFAULT PROPERTY_OWNERS_SEQ.NEXTVAL;
ALTER TABLE TENANTS MODIFY TENANT_ID DEFAULT TENANTS_SEQ.NEXTVAL;
