CREATE SEQUENCE properties_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE property_owners_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE property_listings_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Tenants_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Rental_agreements_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Maintenance_Requests_seq START WITH 1 INCREMENT BY 1;