
create or replace TRIGGER "TR_MAINTENANCE_REQUESTS"
BEFORE INSERT ON "MAINTENANCE_REQUESTS"
FOR EACH ROW
BEGIN
  IF :NEW."REQUEST_ID" IS NULL THEN
    SELECT "MAINTENANCE_REQUESTS_SEQ".NEXTVAL INTO :NEW."REQUEST_ID" FROM sys.dual;
  END IF;
END;
/


create or replace TRIGGER "TR_PROPERTIES"
BEFORE INSERT ON "PROPERTIES"
FOR EACH ROW
BEGIN
  IF :NEW."PROPERTY_ID" IS NULL THEN
    SELECT "PROPERTIES_SEQ".NEXTVAL INTO :NEW."PROPERTY_ID" FROM sys.dual;
  END IF;
END;
/


create or replace TRIGGER "TR_PROPERTY_LISTINGS"
BEFORE INSERT ON "PROPERTY_LISTINGS"
FOR EACH ROW
BEGIN
  IF :NEW."LISTING_ID" IS NULL THEN
    SELECT "PROPERTY_LISTINGS_SEQ".NEXTVAL INTO :NEW."LISTING_ID" FROM sys.dual;
  END IF;
END;
/


create or replace TRIGGER "TR_PROPERTY_OWNERS"
BEFORE INSERT ON "PROPERTY_OWNERS"
FOR EACH ROW
BEGIN
  IF :NEW."OWNER_ID" IS NULL THEN
    SELECT "PROPERTY_OWNERS_SEQ".NEXTVAL INTO :NEW."OWNER_ID" FROM sys.dual;
  END IF;
END;
/


create or replace TRIGGER "TR_RENTAL_AGREEMENTS"
BEFORE INSERT ON "RENTAL_AGREEMENTS"
FOR EACH ROW
BEGIN
  IF :NEW."RENTAL_ID" IS NULL THEN
    SELECT "RENTAL_AGREEMENTS_SEQ".NEXTVAL INTO :NEW."RENTAL_ID" FROM sys.dual;
  END IF;
END;
/



create or replace TRIGGER "TR_TENANTS"
BEFORE INSERT ON "TENANTS"
FOR EACH ROW
BEGIN
  IF :NEW."TENANT_ID" IS NULL THEN
    SELECT "TENANTS_SEQ".NEXTVAL INTO :NEW."TENANT_ID" FROM sys.dual;
  END IF;
END;
/